### ISSUE TITLE
Failed to install tensorflow==2.12.0, nsfw-roop will not work.

### ISSUE THREAD

**Issue by Sansblaze** [Gourieff/sd-webui-roop-nsfw#1]
Idk why it's givin me this error, tried pip install tensorflow==2.12.0 and it said it's already installed . . 

"stdout: The 'tensorflow' distribution was not found and is required by the application
Warning: Failed to install tensorflow==2.12.0, nsfw-roop will not work."

**Comment by Gourieff** [comment]
Try to close sd-web-ui and start it again
That happens sometimes with some components after installation (initialization in venv goes normally only after an environment reloading)
Also you can try to look into `\venv\Lib\site-packages` - if you see folders with names starting from "~" - try to delete them and reinstall the package that calls errors with `--force-reinstall` option inside your venv

**Comment by ResleyZ** [comment]
> Idk why it's givin me this error, tried pip install tensorflow==2.12.0 and it said it's already installed . .
> 
> "stdout: The 'tensorflow' distribution was not found and is required by the application Warning: Failed to install tensorflow==2.12.0, nsfw-roop will not work."

I was getting the same issue, except with diffusers-0.17.1
There was no diffusers or ~ folder in the \venv\lib\site-packages folder.

I managed to fix it by installing it myself and placing it in the venv folder. 
- Use `pip install diffusers-0.17.1` outside of the venv folder. If you do get the message it's already installed, delete the installed folders first using the next command.
- Go to the folder the package is installed in. This can be checked by using `pip show diffusers`
- Copy both package folders, and place it in the \venv\lib\site-packages\ folder. 
- After this I restarted the WebUI, and now it works perfectly

**Comment by Sansblaze** [comment]
> * Use `pip install diffusers-0.17.1` outside of the venv folder. If you do get the message it's already installed, delete the installed folders first using the next command.
> 
> * Go to the folder the package is installed in. This can be checked by using `pip show diffusers`
> 
> * Copy both package folders, and place it in the \venv\lib\site-packages\ folder.
> 
> * After this I restarted the WebUI, and now it works perfectly

Everything seems to work, thanks. I had to put tensorflow, diffusers, and 4 others in \venv\lib\site-packages\
