### ISSUE TITLE
Roop_NSFW and SD.next

### ISSUE THREAD

**Issue by unkleb** [Gourieff/sd-webui-roop-nsfw#11]
Will this work in the new Vlad/vladmandic/automatic?

I have installed and reinstalled several times.  I can never get the model to load.  Always get the warning I should have at least one model.  Inswapper_128.onnx is in ...\extensions\automatic\extensions\sd-webui-roop-nsfw\models\roop.

Thanks.

**Comment by Gourieff** [comment]
Yeah, I've just test it with the VladAutomatic, during the install it loads "inswapper_128.onnx" file into a wrong directory for some reason
Just move the file to "automatic\models\roop"

**Comment by kamilwielgus** [comment]
hey @Gourieff, Both here and in your instruction you're pointing to automatic\models\roop folder for the "inswapper_128.onnx" file but in https://github.com/Gourieff/sd-webui-reactor/blob/main/scripts/faceswap.py#L25 the path that is being built is `automatic\models\insightface`. had to fix it locally for the model to get detected.
