### ISSUE TITLE
No module named 'onnxruntime'

### ISSUE THREAD

**Issue by Nandop2000** [Gourieff/sd-webui-roop-nsfw#16]
When I start Automatic1111 is get the following error: ....\WebUI\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 13, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'

CMD tells me it's already installed when I try to install the module. What can I do to resolve this issue?

**Comment by Nandop2000** [comment]
fixed it by going into venv\Scripts -> CMD activate and python -m pip install force-reinstall onnxruntime==1.15.0

**Comment by eyalgi11** [comment]
i get the same thing but your solution gives me:
ERROR: Could not find a version that satisfies the requirement reinstall (from versions: none)
ERROR: No matching distribution found for reinstall

**Comment by Starzilla29** [comment]
> i get the same thing but your solution gives me: ERROR: Could not find a version that satisfies the requirement reinstall (from versions: none) ERROR: No matching distribution found for reinstall

I have this same issue

**Comment by brian-joseph-petersen** [comment]
you need to remove `force-reinstall` from the pip command. Stop the webui server if it's running, then go to the stable-diffusion-webui install directory and activate the venv. Then, run the pip install command. Don't forget to deactivate the venv.

```
source ./venv/bin/activate

python -m pip install onnxruntime

deactivate
```
