### ISSUE TITLE
Errors on automatic1111

### ISSUE THREAD

**Issue by SonnyCyrus** [Gourieff/sd-webui-roop-nsfw#18]
Any idea?
<img width="899" alt="screenshot" src="https://github.com/Gourieff/sd-webui-roop-nsfw/assets/139864896/2d1beadb-fd78-4cc6-9723-4b861d7c505e">

**Comment by Gourieff** [comment]
If so, just use this [example](../blob/main/example/api_example.py) of how to operate via API
