### ISSUE TITLE
Missing order option

### ISSUE THREAD

**Issue by mykeehu** [Gourieff/sd-webui-roop-nsfw#2]
Very useful is what I saw in the description, that you can set the order of face recovery, but I can't find the option in version 0.1.0:
https://github.com/Gourieff/sd-webui-roop-nsfw/blob/main/example/pp-order.png

Where can I find it or why is it not displayed?

**Comment by Gourieff** [comment]
Thanks for noticing!
**FIXED**
Just `git pull` for update

**Comment by mykeehu** [comment]
Thanks for quick fix!
