### ISSUE TITLE
ComfyUI Nodes

### ISSUE THREAD

**Issue by wknudsen** [Gourieff/sd-webui-roop-nsfw#21]
### Discussed in https://github.com/Gourieff/sd-webui-roop-nsfw/discussions/19

<div type='discussions-op-text'>

<sup>Originally posted by **wknudsen** July 18, 2023</sup>
It would be nice to have ComfyUI nodes for Roop-GE the same way as for the original Roop. I miss the extended Roop functionality when working in ComfyUI. Any possibilities for that?</div>

**Comment by Gourieff** [comment]
Done! 
https://github.com/Gourieff/comfyui-reactor-node
