### ISSUE TITLE
installation on google colab?

### ISSUE THREAD

**Issue by annasophiachristianahahn** [Gourieff/sd-webui-roop-nsfw#25]
Hello!

Has anyone successfully installed Roop on a google colab implementation of Automatic1111? I have found this guide https://github.com/Gourieff/sd-webui-roop-nsfw however it is specifically for installing to Windows- not a colab environment

does anyone know the correct way to make Roop install correctly with automatic1111 on colab?

I am specifically interested in installing Roop to Cagliostro colab fork of automatic1111 - has anyone successfully integrated Roop into cagliostro colab? if so I would be extremely grateful for instructions on how to do this

https://github.com/Linaqruf/sd-notebook-collection

**Comment by Gourieff** [comment]
Hello
You can install it the same way following the instruction from Step 2: https://github.com/Gourieff/sd-webui-roop-nsfw#installation
When you see the message "--- PLEASE, RESTART the Server! ---" - just go to the "Installed" tab and click "Apply and restart UI"
I've just tried to do it, works perfectly

**Comment by Gourieff** [comment]
![01](https://github.com/Gourieff/sd-webui-roop-nsfw/assets/85128026/f9bfcf9d-dec0-4067-97ba-016044f15a7b)
![02](https://github.com/Gourieff/sd-webui-roop-nsfw/assets/85128026/bfe77d44-4ec2-4667-9ca9-889b4a0ed055)
![03](https://github.com/Gourieff/sd-webui-roop-nsfw/assets/85128026/36130ac2-a993-4029-8618-a05f165fd71f)

**Comment by Gourieff** [comment]
@annasophiachristianahahn you can use updated instruction from here https://github.com/Gourieff/sd-webui-roop-nsfw#colab
