### ISSUE TITLE
src/tcmalloc.cc:284] Attempt to free invalid pointer 0x111a1eb80

### ISSUE THREAD

**Issue by miiiz** [Gourieff/sd-webui-roop-nsfw#31]
When executed roop, sd-webui crashed. 
![image](https://github.com/Gourieff/sd-webui-roop-nsfw/assets/11407347/35b679d7-4d69-43c2-9faf-70776b9756d2)

(gets similar error when using original roop)

**Comment by Gourieff** [comment]
You can try to disable "tcmalloc" inside your webui-user.sh:
> ```
> # Uncomment to disable TCMalloc
> #export NO_TCMALLOC="True"
> ```

**Comment by miiiz** [comment]
Thanks for your reply. "tcmalloc" has already been disabled. 

I tried add 
`export LD_PRELOAD="/usr/lib64/libjemalloc.so.1"`
in webui-user.sh and it worked.

**Comment by Gourieff** [comment]
Ok then

Leave here some notes about this issue:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/6722
https://github.com/TheLastBen/fast-stable-diffusion/issues/2347#issuecomment-1642979703
