### ISSUE TITLE
Model not found problem but its there ? help

### ISSUE THREAD

**Issue by Someonetoldme584** [Gourieff/sd-webui-roop-nsfw#5]
![image](https://github.com/Gourieff/sd-webui-roop-nsfw/assets/79592731/83a699c0-2be8-4cc5-8538-2d129cc29189)
![image](https://github.com/Gourieff/sd-webui-roop-nsfw/assets/79592731/541d43dd-d142-4b6e-9e92-2320a237af38)

**Comment by AlexSheff** [comment]
Check the way! The model must be in ....**\stable-diffusion-webui\models\roop** folder!
