### ISSUE TITLE
API Support

### ISSUE THREAD

**Issue by afeezaziz** [Gourieff/sd-webui-roop-nsfw#6]
As per using sd webui, there is an API support but for each of the extension, we need to write the API support on our own. Would you consider to enable this extension to have API support?

**Comment by Gourieff** [comment]
Yes, I was thinking about it, useful feature
Going to implement it soon

**Comment by afeezaziz** [comment]
@Gourieff please let me know if you need help, either via code writing or documentation.

**Comment by Gourieff** [comment]
@afeezaziz ok, noted, thanks!

**Comment by Gourieff** [comment]
@afeezaziz API support is ready! Feel free to test: 
[usage example](../blob/main/example/api_example.py)

**Comment by afeezaziz** [comment]
@Gourieff thank you, I will try it today and let you know soon.
