### ISSUE TITLE
Error running postproccess_image

### ISSUE THREAD

**Issue by gd1147** [Gourieff/sd-webui-roop-nsfw#8]
Receiving the following error.  Have tried multiple options of upscalers and reversing the order of processing.

*** Error running postprocess_image: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 212, in postprocess_image
        upscale_options=self.upscale_options,
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 133, in upscale_options
        return UpscaleOptions(
    TypeError: UpscaleOptions.__init__() got an unexpected keyword argument 'do_restore_first'

**Comment by Gourieff** [comment]
Please, read here how to solve it: https://github.com/Gourieff/sd-webui-roop-nsfw/issues/3

**Comment by gd1147** [comment]
Thank you that fixed it.  Perhaps adding to the install instructions that it cannot co-exist with the original version of Roop would be useful.

**Comment by Gourieff** [comment]
It can co-exist in different directories, this issue takes place, as I suppose, when original Roop extension is manually renamed to this one - so that not all commits become merged during 'git pull' and some files remain outdated

**Comment by gd1147** [comment]
OK, thank you for clarifying.  I am not sure what happened in my case as I didn't do any copying or co mingling of the two.  Deleting all versions and only installing this one did the trick for me.  I can test adding the other version back later and see if it breaks anything.

**Comment by postmrtm** [comment]
I'm getting the following error no matter how i try to resolve and using all the possible answers i found on google :(
please help :(

'FaceSwapScript' object has no attribute 'enable'

**Comment by Gourieff** [comment]
@postmrtm you can try this solution: https://github.com/s0md3v/sd-webui-roop/issues/138

**Comment by postmrtm** [comment]
amazing! that was the issue! i cant believe ive wasted all day because of another extension clash  :(
thank you @Gourieff !

**Comment by Gourieff** [comment]
> OK, thank you for clarifying. I am not sure what happened in my case as I didn't do any copying or co mingling of the two. Deleting all versions and only installing this one did the trick for me. I can test adding the other version back later and see if it breaks anything.

You were right! I test it one more time - and they really can co-exist only if one of extensions is disabled!
I suppose that there is an arguments conflict because of the original Roop initializes first and has less arguments.
I added this moment to the Troubleshooting section of the Readme.
Thanks!
