### ISSUE TITLE
Cannot install on Windows, problem with insightface

### ISSUE THREAD

**Issue by teherauto** [Gourieff/sd-webui-roop-nsfw#9]
Hi,
Sorry, but I cannot install the extension. Follow your installation description, but always get an error message:

venv "c:\ai\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements
*** Error running install.py for extension C:\ai\stable-diffusion-webui\extensions\sd-webui-roop-nsfw.
*** Command: "c:\ai\stable-diffusion-webui\venv\Scripts\python.exe" "C:\ai\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\install.py"
*** Error code: 1
*** stdout: The 'insightface' distribution was not found and is required by the application
*** Warning: Failed to install insightface==0.7.3, nsfw-roop will not work.
***
*** stderr: Traceback (most recent call last):
***   File "C:\ai\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\install.py", line 55, in <module>
***     raise e
***   File "C:\ai\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\install.py", line 40, in <module>
***     installed_version = pkg_resources.get_distribution(package_name).version
***   File "c:\ai\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 478, in get_distribution
***     dist = get_provider(dist)
***   File "c:\ai\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 354, in get_provider
***     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
***   File "c:\ai\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 909, in require
***     needed = self.resolve(parse_requirements(requirements))
***   File "c:\ai\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 795, in resolve
***     raise DistributionNotFound(req, requirers)
*** pkg_resources.DistributionNotFound: The 'insightface' distribution was not found and is required by the application

Launching Web UI with arguments: --api --opt-sdp-attention --xformers
[-] ADetailer initialized. version: 23.7.5, num models: 9
2023-07-08 18:06:18,940 - ControlNet - INFO - ControlNet v1.1.231
ControlNet preprocessor location: C:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-07-08 18:06:19,027 - ControlNet - INFO - ControlNet v1.1.231
2023-07-08 18:06:21,793 - Roop-GE - INFO - Roop-GE v0.2.0
2023-07-08 18:06:21,795 - Roop-GE - INFO - Roop-GE v0.2.0
Loading weights [62e2993f1d] from C:\ai\stable-diffusion-webui\models\Stable-diffusion\epicrealism_pureEvolution.safetensors
Creating model from config: C:\ai\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Running on local URL:  http://127.0.0.1:7860

Off course I did install manually the insightface, "pip list" show in the list:
![kép](https://github.com/Gourieff/sd-webui-roop-nsfw/assets/6264591/8f62b54c-351a-4d0c-a832-367af1f770d0)

What can I do more?

**Comment by teherauto** [comment]
Ok, I found the problem: I installed the insightface with the normal Python, not with the a1111 Python. The two different python using different pip, and install different apps. So, just installed with the a1111 python's pip the insightface, and working fine.

**Comment by thenotrealuser** [comment]
How you do that?

venv "C:\stable diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.4.0-2-g8d0078b6
Commit hash: 8d0078b6ef280f43efd7cccc2ea673dccdd1c0aa
Installing requirements
*** Error running install.py for extension C:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw.
*** Command: "C:\stable diffusion\stable-diffusion-webui\venv\Scripts\python.exe" "C:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\install.py"
*** Error code: 1
*** stdout: The 'insightface' distribution was not found and is required by the application
*** Warning: Failed to install insightface==0.7.3, nsfw-roop will not work.
***
*** stderr: Traceback (most recent call last):
***   File "C:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\install.py", line 52, in <module>
***     raise e
***   File "C:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\install.py", line 37, in <module>
***     installed_version = pkg_resources.get_distribution(package_name).version
***   File "C:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 478, in get_distribution
***     dist = get_provider(dist)
***   File "C:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 354, in get_provider
***     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
***   File "C:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 909, in require
***     needed = self.resolve(parse_requirements(requirements))
***   File "C:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 795, in resolve
***     raise DistributionNotFound(req, requirers)
*** pkg_resources.DistributionNotFound: The 'insightface' distribution was not found and is required by the application
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
2023-07-10 17:37:31,154 - Roop-GE - INFO - Roop-GE v0.2.0
2023-07-10 17:37:31,156 - Roop-GE - INFO - Roop-GE v0.2.0
Loading weights [a8e08b582e] from C:\stable diffusion\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV30_v30VAE.safetensors
preload_extensions_git_metadata for 8 extensions took 0.20s
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 10.2s (import torch: 3.1s, import gradio: 1.4s, import ldm: 0.7s, other imports: 2.0s, setup codeformer: 0.1s, load scripts: 1.8s, create ui: 0.6s, gradio launch: 0.3s).
Creating model from config: C:\stable diffusion\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: Doggettx... done.
Textual inversion embeddings loaded(0):
Model loaded in 24.6s (load weights from disk: 1.0s, create model: 0.5s, apply weights to model: 10.2s, apply half(): 11.3s, move model to device: 0.9s, load textual inversion embeddings: 0.2s, calculate empty prompt: 0.3s).
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  2.92it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.24it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.59it/s]
*** Error running postprocess_image: C:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py███████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  4.72it/s]
    Traceback (most recent call last):
      File "C:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 206, in postprocess_image
        result: ImageResult = swap_face(
      File "C:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 171, in swap_face
        source_face = get_face_single(source_img, face_index=source_faces_index[0])
      File "C:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 119, in get_face_single
        face_analyser = insightface.app.FaceAnalysis(name="buffalo_l", providers=providers)
    AttributeError: module 'insightface' has no attribute 'app'

---
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.51it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.72it/s]

Im trying to install via pip from a1111 but, how it works?

**Comment by foggy54** [comment]
Hello, @teherauto can you please provide more information on how to install pip packages with a1111's python? I have similar problem.

**Comment by teherauto** [comment]
I change the directory to C:\stable diffusion\stable-diffusion-webui\venv\Scripts\ in command line and start the Activate.bat, and run in the shell the "pip install insightface" command.

If I simply typed "pip install insightface", the Windows installed Python started because it is in the PATH, and that "pip list" listed the insightface modul when checked the installed moduls.
